##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;


#	root /usr/share/nginx/html;
	root /var/www/node-js-dummy-test/public;
#	root /var/www/html;
	# Add index.php to the list if you are using PHP
#	index index.html index.htm index.nginx-debian.html;
#	index index.ejs index.js index.test.js
	server_name a.claudghazni.online www.a.claudghazni.online;

#	location /static {
#	    root /var/www/html;
#	    expires 48d;
#	}



#  location / {
#    try_files $uri $uri/ @apache;
#  }

#  location @apache {
#    proxy_pass http://127.0.0.1:81;
#    proxy_set_header Host $host;
#    proxy_set_header X-Real-IP $remote_addr;
#    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#    proxy_set_header X-Forwarded-Proto $scheme;
    #proxy_set_header X-Forwarded-Port $server_port;
    #proxy_set_header X-Forwarded-Host $host;
    #proxy_buffering on;
    #proxy_cache_bypass $http_pragma;
    #proxy_cache_revalidate on;
    #proxy_cache_valid 200 60m;
   # proxy_cache_valid 404 1m;
   # proxy_cache_bypass $http_pragma;
    #proxy_cache_revalidate on;
#  }


#  include snippets/letsencrypt.conf;





	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
#
		

		 #auth_basic "Restricted Content";
        	#auth_basic_user_file /etc/nginx/.htpasswd;
	        proxy_pass http://a.claudghazni.online:3005;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
#		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#	        proxy_set_header X-Forwarded-Proto $scheme;

	
	}

#	location /api/ {
#         proxy_pass http://127.0.0.1:3001;
#         proxy_http_version 1.1;
#         proxy_set_header Connection '';
#         proxy_set_header Host $host;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $remote_addr;
#    }

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/run/php/php7.4-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#

server {
        listen 80;
        listen [::]:80;

        server_name b.claudghazni.online;

        root /var/www/node-js-sample;
        #index index.html;

        location / {
                try_files $uri $uri/ =404;
        proxy_pass http://b.claudghazni.online:5005;
        }
}

#server {
    #    listen 80;
    #    listen [::]:80;

   #     server_name b.claudghazni.online;

   #     root /var/www/roundcube/installer/;
   #     index index.php;

  #      location / {
  #      try_files $uri $uri/ /index.php?$args;

#                try_files $uri $uri/ =404;
#        proxy_pass http://b.claudghazni.online:5005;
 #       }

 #   location ~ \.php$ {
 #       include fastcgi_params;
 #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
 #       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
 #   }
#}



#server {
#	listen 80;
#	listen [::]:80;

#	server_name example.com;

#	root /var/www/example.com;
#	index index.html;

#	location / {
#		try_files $uri $uri/ =404;
#	}
#}
